version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: auto_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auto_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/tables_mysql_innodb.sql:/docker-entrypoint-initdb.d/01-tables.sql
      - ./src/main/resources/quartz_tables_mysql.sql:/docker-entrypoint-initdb.d/02-quartz.sql
    networks:
      - auto_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      timeout: 20s
      retries: 10

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auto_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      TZ: Asia/Ho_Chi_Minh
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - auto_network
    restart: unless-stopped
    volumes:
      - ./src/main/resources/firebase-service-account.json:/app/firebase-service-account.json

volumes:
  mysql_data:

networks:
  auto_network:
    driver: bridge